---
#Purpose: The AWS CloudFormation template version that the template conforms to. 
#Required?: Optional
AWSTemplateFormatVersion: "2010-09-09"

#Purpose: A text String that describes the template
#Required?: Optional!, but must follow AWSTemplateFormatVersion
Description:
  Creates a new subnet, with a specific CIDR, in a specific VPC and availability zone
  and adds and instance to it

#Purpose: Specifies the stack resources and their properties, such as EC2, S3. 
#References: Resources and Outputs Section, can refer to this section. 
#Required?: Required!
Resources:
  EC2Subnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "us-east-1a"
      CidrBlock: "172.31.96.0/20"
      MapPublicIpOnLaunch: false 
      Tags: 
        - Key: foo 
          Value: bar
      VpcId: vpc-0e68cbb890311599b
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: "us-east-1a"
      ImageId: ami-0323c3dd2da7fb37d
      KeyName: keypair